#!/bin/bash
WHAT=$1
FN=$2
if [ ! -f "$FN" ]; then
    echo "$FN does not exist. Trying $AETHER_REST/$FN"
    FN=$AETHER_REST/$FN
fi
if [ ! -f "$FN" ]; then
    echo "$FN does not exist"
    exit
fi
STUFF=`cat $FN`

IP=`kubectl -n micro-onos get service | grep -i aether-roc-api | awk '{print $3}'`
URL="http://$IP:8181/aether/v1.0.0/connectivity-service-v1/$WHAT"
curl --location --request POST $URL \
    --header 'Content-Type: application/json' \
    --data "$STUFF"
