#!/bin/bash
set -e
source /usr/bin/c-aether
export ONOS_CONFIG_VERSION=smbaker
export KIND_CLUSTER_NAME=voltha-minimal
cd /home/smbaker/projects/aether/config-models/modelplugin/aether-1.0.0
make models
cd /home/smbaker/projects/aether/config-models/modelplugin/aether-2.0.0
make models
cd /home/smbaker/projects/aether/config-models/modelplugin/enterprise-1.0.0
make models
cd ../..
make images && make kind-only
