#!/bin/bash
set -e
pushd /home/smbaker/projects/aether/aether-roc-api
#export DOCKER_REPOSITORY=smbaker/
#export ONOS_TOPO_VERSION=smbaker
#export KIND_CLUSTER_NAME=voltha-minimal
make images
#make kind-only
docker tag onosproject/aether-roc-api:latest smbaker/aether-roc-api:smbaker
popd
