#!/bin/bash
set -e
source /usr/bin/c-aether
pushd /home/smbaker/projects/aether/aether-roc-gui
export AETHER_ROC_GUI_VERSION=smbaker
export KIND_CLUSTER_NAME=voltha-minimal
make images
make kind
popd
