#!/bin/bash
set -e
pushd /home/smbaker/projects/aether/aether-roc-api
#export DOCKER_REPOSITORY=smbaker/
#export ONOS_TOPO_VERSION=smbaker
#export KIND_CLUSTER_NAME=voltha-minimal
make images
#make kind-only

source /usr/bin/c-aether
docker tag onosproject/aether-roc-api:latest ${DOCKER_REPOSITORY}aether-roc-api:smbaker
popd
