#!/bin/bash
set -e
source /usr/bin/c-aether
pushd /home/smbaker/projects/aether/onos-topo
export ONOS_TOPO_VERSION=smbaker
export KIND_CLUSTER_NAME=voltha-minimal
make images
make kind-only
#docker tag onosproject/onos-topo:latest smbaker/onos-topo:smbaker
popd
