#!/bin/bash
set -e
source /usr/bin/c-aether
pushd /home/smbaker/projects/aether/sdcore-adapter
export ONOS_SDCORE_ADAPTER_VERSION=smbaker
export KIND_CLUSTER_NAME=voltha-minimal
make images
make kind-only
popd
