#!/bin/bash
if [ $# -eq 0 ]; then
  kubectl -n micro-onos exec -it $(kubectl -n micro-onos get pods -l type=cli --field-selector status.phase=Running -o name) -- /bin/sh
else
  kubectl -n micro-onos exec -it $(kubectl -n micro-onos get pods -l type=cli --field-selector status.phase=Running -o name) -- /usr/local/bin/onos $@
fi
