#!/bin/bash
POD=$(kubectl -n micro-onos get pods -o name | grep -i sdcore-adapter | grep v2)
echo $POD
kubectl -n micro-onos exec -it $POD -- curl -X POST "http://localhost:8080/pull?target=connectivity-service-v2&aetherConfigAddr=onos-config:5150"
