#!/bin/bash
FN=$1
if [ ! -f "$FN" ]; then
    echo "$FN does not exist. Trying $AETHER_REST/$FN"
    FN=$AETHER_REST/$FN
fi
if [ ! -f "$FN" ]; then
    echo "$FN does not exist"
    exit
fi
STUFF=`cat $FN`

IP=`kubectl -n omec get service | grep -i spgwc | grep -v headless | awk '{print $3}'`
URL="http://$IP:8080/v1/config"
curl --location --request POST $URL \
    --header 'Content-Type: application/json' \
    --data "$STUFF"
